# Generated by Django 4.2.7 on 2025-07-03 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('end_time', models.DateTimeField(verbose_name='Время окончания')),
                ('duration', models.PositiveIntegerField(verbose_name='Продолжительность (мин)')),
                ('guests_count', models.PositiveIntegerField(verbose_name='Количество гостей')),
                ('status', models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждено'), ('active', 'Активно'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('no_show', 'Не явился')], default='pending', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('special_requests', models.TextField(blank=True, verbose_name='Особые пожелания')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Контактное имя')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Контактный email')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Сумма депозита')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Общая сумма')),
                ('is_deposit_paid', models.BooleanField(default=False, verbose_name='Депозит оплачен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Причина отмены')),
                ('source', models.CharField(default='website', max_length=50, verbose_name='Источник бронирования')),
                ('notes', models.TextField(blank=True, verbose_name='Внутренние заметки')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='restaurant.table', verbose_name='Столик')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Действие')),
                ('old_status', models.CharField(blank=True, max_length=20, verbose_name='Старый статус')),
                ('new_status', models.CharField(blank=True, max_length=20, verbose_name='Новый статус')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bookings.booking', verbose_name='Бронирование')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'История бронирования',
                'verbose_name_plural': 'История бронирований',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за единицу')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='bookings.booking', verbose_name='Бронирование')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.menuitem', verbose_name='Блюдо')),
            ],
            options={
                'verbose_name': 'Блюдо в бронировании',
                'verbose_name_plural': 'Блюда в бронировании',
                'unique_together': {('booking', 'menu_item')},
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date', 'start_time'], name='bookings_bo_date_c2c738_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['table', 'start_time'], name='bookings_bo_table_i_c97f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'start_time'], name='bookings_bo_user_id_7b21ce_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='bookings_bo_status_233e96_idx'),
        ),
    ]
