# Generated by Django 4.2.7 on 2025-07-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingmenuitem',
            old_name='price',
            new_name='price_per_item',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_deposit_paid',
        ),
        migrations.AddField(
            model_name='booking',
            name='table_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена столика'),
        ),
    ]
